# Generated by Django 5.1.1 on 2024-12-22 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=20)),
                ('fecha_reserva', models.DateField()),
                ('hora', models.TimeField()),
                ('cantidad_personas', models.IntegerField()),
                ('estado', models.CharField(choices=[('RESERVADO', 'Reservado'), ('COMPLETADA', 'Completada'), ('ANULADA', 'Anulada'), ('NO ASISTEN', 'No asisten')], max_length=20)),
                ('observacion', models.TextField(blank=True)),
            ],
        ),
    ]
