# Generated by Django 5.1.1 on 2024-12-22 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservasAPP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(max_length=20),
        ),
    ]
